# This file was generated by GoReleaser. DO NOT EDIT.
cask "nrflow" do
  version "0.2.5"

  on_macos do
    on_intel do
      url "https://github.com/nrflow/nrflow/releases/download/v#{version}/nrflow_#{version}_darwin_amd64.tar.gz"
      sha256 "be78371e1da3c86c557c0debce2f61e6c6caaae030fc69bb77f6e823c71e918f"
    end
    on_arm do
      url "https://github.com/nrflow/nrflow/releases/download/v#{version}/nrflow_#{version}_darwin_arm64.tar.gz"
      sha256 "58f2262383cbf3f3cc9934568fd02abcc5b11b1c7991eb615527e00c6c2a2d50"
    end
  end

  name "nrflow"
  desc "Multi-workflow agent orchestration system"
  homepage "https://github.com/nrflow/nrflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nrflow"
  binary "nrflow_server"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required

  caveats <<~EOS
    Database is stored at ~/.nrflow/nrflow.data by default.
    Override with NRFLOW_HOME environment variable.

    To start the server: nrflow_server serve
  EOS
end
