# This file was generated by GoReleaser. DO NOT EDIT.
cask "nrflow" do
  version "0.2.3"

  on_macos do
    on_intel do
      url "https://github.com/nrflow/nrflow/releases/download/v#{version}/nrflow_#{version}_darwin_amd64.tar.gz"
      sha256 "3a54f4ed70d6bb5d86ef0f66765c22b81e152b2b329d4f721931403f81246bd8"
    end
    on_arm do
      url "https://github.com/nrflow/nrflow/releases/download/v#{version}/nrflow_#{version}_darwin_arm64.tar.gz"
      sha256 "077d8c9f19175773866d67e3f326609f73bf8c76455c663dfb883334b78a6100"
    end
  end

  name "nrflow"
  desc "Multi-workflow agent orchestration system"
  homepage "https://github.com/nrflow/nrflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nrflow"
  binary "nrflow_server"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required

  caveats <<~EOS
    Database is stored at ~/.nrflow/nrflow.data by default.
    Override with NRFLOW_HOME environment variable.

    To start the server: nrflow_server serve
  EOS
end
