# This file was generated by GoReleaser. DO NOT EDIT.
cask "nrflo" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "ab621ce2636baf138a00a54d544634c3627fde3bc469b2550f2d9ec54630eec1"
      url "https://github.com/nrflo/nrflo/releases/download/v#{version}/nrflo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1390233a1e4796b3caa49c6f7536a7730f41371fc6dee5856401d41ce2a15663"
      url "https://github.com/nrflo/nrflo/releases/download/v#{version}/nrflo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d67fd76449b613b166a71b7e690221d4473b2b55c3a468cfa2d4b6fe52280ab3"
      url "https://github.com/nrflo/nrflo/releases/download/v#{version}/nrflo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7f3e59006c85b1b3c5c8a1a37d2b153c6681b022a8e452b6fa13cd4056e8be70"
      url "https://github.com/nrflo/nrflo/releases/download/v#{version}/nrflo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nrflo"
  desc "Multi-workflow agent orchestration system"
  homepage "https://github.com/nrflo/nrflo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nrflo"
  binary "nrflo_server"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required

  caveats <<~EOS
    Database is stored at ~/.nrflo/nrflo.data by default.
    Override with NRFLO_HOME environment variable.

    To start the server: nrflo_server
    Then open http://localhost:6587

    Default login (change on first sign-in):
      Username: admin
      Password: admin

    Rotate credentials in Settings -> Administration -> Users.
  EOS
end
