# This file was generated by GoReleaser. DO NOT EDIT.
cask "nrflow" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/nrflow/nrflow/releases/download/v#{version}/nrflow_#{version}_darwin_amd64.tar.gz"
      sha256 "a5d0bbfbc3296fa10a3a7c3f6213ec1f98229c5986d6e65b8fe3b42157513928"
    end
    on_arm do
      url "https://github.com/nrflow/nrflow/releases/download/v#{version}/nrflow_#{version}_darwin_arm64.tar.gz"
      sha256 "e9fb36932fb0c1f8ccc0f2ad2fa2b64b3187ffff3480465b4380b4f1fc3d522b"
    end
  end

  name "nrflow"
  desc "Multi-workflow agent orchestration system"
  homepage "https://github.com/nrflow/nrflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nrflow"
  binary "nrflow_server"

  # No zap stanza required

  caveats <<~EOS
    Database is stored at ~/.nrflow/nrflow.data by default.
    Override with NRFLOW_HOME environment variable.

    To start the server: nrflow_server serve
  EOS
end
