# This file was generated by GoReleaser. DO NOT EDIT.
cask "nrflo" do
  version "0.3.1"

  on_macos do
    on_intel do
      url "https://github.com/nrflo/nrflo/releases/download/v#{version}/nrflo_#{version}_darwin_amd64.tar.gz"
      sha256 "3d9ca3e7cf53dd5456f147afda0afa3a3f312e4b892c27ce14bc1801549a6f69"
    end
    on_arm do
      url "https://github.com/nrflo/nrflo/releases/download/v#{version}/nrflo_#{version}_darwin_arm64.tar.gz"
      sha256 "aef04365bb14d9514789498c4ad737019385f2e9530ae54733100e5e27b233eb"
    end
  end

  name "nrflo"
  desc "Multi-workflow agent orchestration system"
  homepage "https://github.com/nrflo/nrflo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nrflo"
  binary "nrflo_server"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required

  caveats <<~EOS
    Database is stored at ~/.nrflo/nrflo.data by default.
    Override with NRFLO_HOME environment variable.

    To start the server: nrflo_server serve
  EOS
end
