# This file was generated by GoReleaser. DO NOT EDIT.
cask "nrflo" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "8431bd732a83c6c7339ec9af3ce38431e8d6889fed1fa69fdbb3789e2e22cce1"
      url "https://github.com/nrflo/nrflo/releases/download/v#{version}/nrflo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ed33877274ee674eafb7af86591900b206be318d41808439a207b12d7802b900"
      url "https://github.com/nrflo/nrflo/releases/download/v#{version}/nrflo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "598fb406cc0330f9b38bff128e62f55546d6da0eb45a4e35870613a9353d5db0"
      url "https://github.com/nrflo/nrflo/releases/download/v#{version}/nrflo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e91e5a44301d38cf3dd2d190f3df598dafc949e560e0f6c3e563aec194501f5b"
      url "https://github.com/nrflo/nrflo/releases/download/v#{version}/nrflo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nrflo"
  desc "Multi-workflow agent orchestration system"
  homepage "https://github.com/nrflo/nrflo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nrflo"
  binary "nrflo_server"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required

  caveats <<~EOS
    Database is stored at ~/.nrflo/nrflo.data by default.
    Override with NRFLO_HOME environment variable.

    To start the server: nrflo_server
    Then open http://localhost:6587

    Default login (change on first sign-in):
      Username: admin
      Password: admin

    Rotate credentials in Settings -> Administration -> Users.
  EOS
end
